//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoCentralWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspacioEstacionamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EspacioEstacionamiento()
        {
            this.MovimientoEstacionamiento = new HashSet<MovimientoEstacionamiento>();
        }
    
        public int IdEspacio { get; set; }
        public string CodigoEspacio { get; set; }
        public string TipoEspacio { get; set; }
        public string Estado { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoEstacionamiento> MovimientoEstacionamiento { get; set; }
    }
}
