//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoCentralWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoEstacionamiento
    {
        public int IdMovimiento { get; set; }
        public int IdVehiculo { get; set; }
        public int IdEspacio { get; set; }
        public System.DateTime FechaHoraEntrada { get; set; }
        public Nullable<System.DateTime> FechaHoraSalida { get; set; }
        public string EstadoMovimiento { get; set; }
        public Nullable<decimal> MontoCobrado { get; set; }
        public string UsuarioRegistro { get; set; }
    
        public virtual EspacioEstacionamiento EspacioEstacionamiento { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
