//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoCentralWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParqueoCentralDBEntities : DbContext
    {
        public ParqueoCentralDBEntities()
            : base("name=ParqueoCentralDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<EspacioEstacionamiento> EspacioEstacionamiento { get; set; }
        public virtual DbSet<MovimientoEstacionamiento> MovimientoEstacionamiento { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
    }
}
